banks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from banks.views import *

urlpatterns = [
    path("graph/", graph, name="graph"),
    path("graph1/", graph1, name="graph1"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

liquidity/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls import url

from banks.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Start.as_view()),
    path('home/', Home.as_view()),
    path('about/', About.as_view()),

    path('bank_acc/<bank_acc>', Account.as_view(), name = 'account'),
    path('update/<bank_acc>/<date>',update_view),
    path('updatedeal/<deal_number>',update_deal),
    path('depo/', DepoDeal.as_view()),
    path('spot/', SpotDeal.as_view()),
    path('txfr/', TransferDeal.as_view()),
    path('fwd/', ForwardDeal.as_view()),
    path('dealsearch/', DealSearch.as_view(), name = 'search'),
    path('dealsearch_id/', DealSearchId.as_view(), name = 'search_id'),
    path('dealsfilter/', dealsfilter, name = 'deal-search'),
    path('dataimport/', DataImport.as_view(), name = 'data-import'),
    path('marketdataimport/', MarketDataImport.as_view(), name = 'market-data-import'),
    path('upload/', upload, name = 'upload'),
    path('fxvalue/', dik),

    url(r'^api/chart/data/$', ChartData.as_view()),
    path('chart/', ChartView.as_view()),
    path('api/chart/data2/<bank_acc>', ChartData2.as_view()),
    path('chart2/<bank_acc>', ChartView2.as_view()),
    path('api/yieldchart/data/', YieldChartData.as_view()),
    path('yieldchart/', YieldChartView.as_view()),

    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^add_user/$', AddUser.as_view(), name='add-user'),
    url(r'^reset_password/(?P<user_id>\d+)$', ResetPassword.as_view(), name='reset-password'),

    path('curves/', YieldCurves.as_view(), name = 'curves'),

    url(r'^accounts/', include('allauth.urls')),

    path('przelicznik/', Przelicznik.as_view()),
    path('', include('banks.urls')),
    url(r'^deals/', deals),

    path("mat/", chartDemo.as_view()),
  
]

banks/models.py
from datetime import timedelta
from django.db import models

YES_NO = (("YES", "YES"), ("NO", "NO"))


class Citi(models.Model):
    date = models.DateField(primary_key=True)
    start_balance = models.FloatField(default=0)
    end_balance = models.FloatField(default=0)
    inflows = models.FloatField(default=0)
    outflows = models.FloatField(default=0)
    transfer_in = models.FloatField(default=0)
    transfer_out = models.FloatField(default=0)
    depo = models.FloatField(default=0)
    interest = models.FloatField(default=0)
    reconciliation = models.FloatField(default=0)
    reconciled = models.CharField(choices=YES_NO, max_length=3, default="NO")

    @property
    def result(self):
        return (
            self.inflows
            + self.outflows
            + self.transfer_in
            + self.transfer_out
            + self.depo
            + self.interest
        )

    @property
    def end(self):
        return self.start_balance + self.result


class mBank(models.Model):
    date = models.DateField(primary_key=True)
    start_balance = models.FloatField(default=0)
    end_balance = models.FloatField(default=0)
    inflows = models.FloatField(default=0)
    outflows = models.FloatField(default=0)
    transfer_in = models.FloatField(default=0)
    transfer_out = models.FloatField(default=0)
    depo = models.FloatField(default=0)
    interest = models.FloatField(default=0)
    reconciliation = models.FloatField(default=0)
    reconciled = models.CharField(choices=YES_NO, max_length=3, default="NO")

    @property
    def result(self):
        return (
            self.inflows
            + self.outflows
            + self.transfer_in
            + self.transfer_out
            + self.depo
            + self.interest
        )

    @property
    def end(self):
        return self.start_balance + self.result


class Societe(models.Model):
    date = models.DateField(primary_key=True)
    start_balance = models.FloatField(default=0)
    end_balance = models.FloatField(default=0)
    inflows = models.FloatField(default=0)
    outflows = models.FloatField(default=0)
    transfer_in = models.FloatField(default=0)
    transfer_out = models.FloatField(default=0)
    depo = models.FloatField(default=0)
    interest = models.FloatField(default=0)
    reconciliation = models.FloatField(default=0)
    reconciled = models.CharField(choices=YES_NO, max_length=3, default="NO")

    @property
    def result(self):
        return (
            self.inflows
            + self.outflows
            + self.transfer_in
            + self.transfer_out
            + self.depo
            + self.interest
        )

    @property
    def end(self):
        return self.start_balance + self.result


class Santander(models.Model):
    date = models.DateField(primary_key=True)
    start_balance = models.FloatField(default=0)
    end_balance = models.FloatField(default=0)
    inflows = models.FloatField(default=0)
    outflows = models.FloatField(default=0)
    transfer_in = models.FloatField(default=0)
    transfer_out = models.FloatField(default=0)
    depo = models.FloatField(default=0)
    interest = models.FloatField(default=0)
    reconciliation = models.FloatField(default=0)
    reconciled = models.CharField(choices=YES_NO, max_length=3, default="NO")

    @property
    def result(self):
        return (
            self.inflows
            + self.outflows
            + self.transfer_in
            + self.transfer_out
            + self.depo
            + self.interest
        )

    @property
    def end(self):
        return self.start_balance + self.result


DEAL_KIND = (("DEPO", "DEPO"), ("TXFR", "TXFR"), ("FX", "FX"), ("FWD", "FWD"))

CURRENCY = (("PLN", "PLN"), ("EUR", "EUR"), ("USD", "USD"))

CROSS_CURRENCY = (
    ("EUR/PLN", "EUR/PLN"),
    ("USD/PLN", "USD/PLN"),
    ("EUR/USD", "EUR/USD"),
)

DEAL_SIDE = (("BUY", "BUY"), ("SELL", "SELL"))

COUNTERPARTY = (
    ("Citi", "Citi"),
    ("mBank", " mBank"),
    ("Societe", "Societe"),
    ("Santander", "Santander"),
)

"""class Counterparty(models.Model):
    name = models.CharField(max_length=20, null=False)
    short = models.CharField(max_length=10, null=False)
    pln_acc = models.CharField(max_length=20, null=True)"""


class Books(models.Model):
    date = models.DateField(primary_key=True)
    inflows = models.FileField(null=True, max_length=100)
    outflows = models.FileField(null=True, max_length=100)


class Deals(models.Model):
    deal_number = models.AutoField(primary_key=True)
    deal_date = models.DateField(null=True)
    value_date = models.DateField(null=True)
    expiry_date = models.DateField(null=True)
    deal_kind = models.CharField(choices=DEAL_KIND, max_length=20, null=True)
    currency_base = models.CharField(choices=CURRENCY, null=True, max_length=3)
    currency_side = models.CharField(choices=CURRENCY, null=True, max_length=3)
    currency_cross = models.CharField(choices=CROSS_CURRENCY, null=True, max_length=7)
    side = models.CharField(choices=DEAL_SIDE, null=True, max_length=20)
    counterparty = models.CharField(choices=COUNTERPARTY, null=True, max_length=30)
    counterparty_another = models.CharField(choices=COUNTERPARTY, null=True, max_length=30)
    amount_in_base_cur = models.FloatField(null=True)
    amount_in_side_cur = models.FloatField(null=True)
    exchange_rate = models.FloatField(null=True)
    forward_rate = models.FloatField(null=True)
    interest_rate = models.FloatField(null=True)
    interest_rate_amount = models.FloatField(null=True)
    basis = models.CharField(null=True, max_length=20)
    frontoffice = models.CharField(null=True, max_length=10)
    fronttime = models.DateTimeField(null=True)
    middleoffice = models.CharField(null=True, max_length=10)
    middletime = models.DateTimeField(null=True)
    backoffice = models.CharField(null=True, max_length=10)
    backtime = models.DateTimeField(null=True)
    entity = models.CharField(null=True, max_length=20)
    status = models.CharField(null=True, max_length=10)
    cancel_user = models.CharField(null=True, max_length=10)
    cancel_time = models.DateTimeField(null=True)
    strategy_code = models.CharField(null=True, max_length=32)
    comment = models.CharField(null=True, max_length=160)

    @property
    def name(self):
        return "{} | {} | {} | {} | {} | {}".format(
            self.deal_number,
            self.counterparty,
            self.deal_kind,
            self.deal_date,
            self.value_date,
            self.amount_in_base_cur,
        )

    def __str__(self):
        return self.name


class PlnCurve(models.Model):
    date = models.DateField(primary_key=True)
    m1 = models.FloatField(default=0)
    m3 = models.FloatField(default=0)
    m6 = models.FloatField(default=0)
    y1 = models.FloatField(default=0)
    y2 = models.FloatField(default=0)
    y3 = models.FloatField(default=0)
    y4 = models.FloatField(default=0)
    y5 = models.FloatField(default=0)
    y6 = models.FloatField(default=0)
    y7 = models.FloatField(default=0)
    y8 = models.FloatField(default=0)
    y9 = models.FloatField(default=0)
    y10 = models.FloatField(default=0)
    y12 = models.FloatField(default=0)
    y15 = models.FloatField(default=0)
    y20 = models.FloatField(default=0)


class EurCurve(models.Model):
    date = models.DateField(primary_key=True)
    m1 = models.FloatField(default=0)
    m3 = models.FloatField(default=0)
    m6 = models.FloatField(default=0)
    y1 = models.FloatField(default=0)
    y2 = models.FloatField(default=0)
    y3 = models.FloatField(default=0)
    y4 = models.FloatField(default=0)
    y5 = models.FloatField(default=0)
    y6 = models.FloatField(default=0)
    y7 = models.FloatField(default=0)
    y8 = models.FloatField(default=0)
    y9 = models.FloatField(default=0)
    y10 = models.FloatField(default=0)
    y12 = models.FloatField(default=0)
    y15 = models.FloatField(default=0)
    y20 = models.FloatField(default=0)
    y30 = models.FloatField(default=0)
    y50 = models.FloatField(default=0)


class UsdCurve(models.Model):
    date = models.DateField(primary_key=True)
    m1 = models.FloatField(default=0)
    m3 = models.FloatField(default=0)
    m6 = models.FloatField(default=0)
    y1 = models.FloatField(default=0)
    y2 = models.FloatField(default=0)
    y3 = models.FloatField(default=0)
    y4 = models.FloatField(default=0)
    y5 = models.FloatField(default=0)
    y6 = models.FloatField(default=0)
    y7 = models.FloatField(default=0)
    y8 = models.FloatField(default=0)
    y9 = models.FloatField(default=0)
    y10 = models.FloatField(default=0)
    y12 = models.FloatField(default=0)
    y15 = models.FloatField(default=0)
    y20 = models.FloatField(default=0)
    y30 = models.FloatField(default=0)
    y50 = models.FloatField(default=0)

class PLN1M (models.Model):
    date = models.DateField(primary_key=True)
    d1 = models.FloatField(default=0)
    m1 = models.FloatField(default=0)
    m3 = models.FloatField(default=0)
    m6 = models.FloatField(default=0)
    m9 = models.FloatField(default=0)
    y1 = models.FloatField(default=0)
    y2 = models.FloatField(default=0)

class PLN3M (models.Model):
    date = models.DateField(primary_key=True)
    d1 = models.FloatField(default=0)
    m1 = models.FloatField(default=0)
    m3 = models.FloatField(default=0)
    m6 = models.FloatField(default=0)
    m9 = models.FloatField(default=0)
    y1 = models.FloatField(default=0)
    y2 = models.FloatField(default=0)
    y3 = models.FloatField(default=0)
    y4 = models.FloatField(default=0)
    y5 = models.FloatField(default=0)
    y6 = models.FloatField(default=0)
    y7 = models.FloatField(default=0)
    y8 = models.FloatField(default=0)
    y9 = models.FloatField(default=0)
    y10 = models.FloatField(default=0)

class PLN6M (models.Model):
    date = models.DateField(primary_key=True)
    d1 = models.FloatField(default=0)
    m1 = models.FloatField(default=0)

banks/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/about.css' %}">

<div id=container>
        Make 
        <div id=flip>
          <div><div>wOrK</div></div>
          <div><div>life</div></div>
          <div><div>Everything</div></div>
        </div>
        EASIER!
</div>

<div class="box">

    <p>Dear User,</p>

    <p> <span class="bolder">Liquidity Manager</span> app was created to handle front-, middle- and back-office work flow of medium sized corporate. 
        My aim is to make all processes as smooth as possible with friendly user experience. Back-end of aplication is 
        built with <span class="bol">Phyton (Django framework)</span>  supported by <span class="bol">PostgreSQL</span>  database. User experience is handled by <span class="bol"> JavaScript,
        jQuery UI </span>and <span class="bol">Font Awesome</span>.
    </p>

    <p>Best of luck!</p>
    <p>Artur</p>

</div>
{% endblock %}

banks/templates/base1.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{{title}}</title>

    <!-- Bootstrap 4 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

    <!-- Font Awesome -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">



  </head>
  <body>
    {% include 'navbar.html' %}

      {% block content %}
            
      {% endblock %}

  </body>

<link rel="stylesheet" type="text/css" href="/jquery.datetimepicker.css"/ >
<script src="/jquery.js"></script>
<script src="/build/jquery.datetimepicker.full.min.js"></script>


</html>

banks/templates/deal_search.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/ticket.css' %}">
<script src="{% static 'js/app.js' %}"></script>

<form action="" method="get" id="sf">

  <h2 id="ticket_center">Deal search</h2>
  <hr>
  {% for field in form %}
  <div class="textWrapper">
    <br>
    {{field.label_tag}} {{field}}

  </div>
  {% endfor %}
  <br>
  <input id="but" type="submit" value="Search" class="textWrapper button_form">
  <br>
  <br>
</form>


<script>
  var a = "deal search works"
      console.log(a)
  $(document).ready(function () {
    $('#sf').submit(function (event) {
      var filterParams = {};
      

      filterParams['number_contains'] = $('#id_number_contains').val();
      filterParams['start_date'] = $('#id_start_date').val();
      filterParams['id_end_date'] = $('#id_end_date').val();
      filterParams['counterparty'] = $('#id_counterparty').val();
      filterParams['date_choice'] =$('input[name="date_choice"]:checked').val();
      filterParams['view_type'] = 'ajax';
      $.get('/dealsearch/',filterParams,function(data){
        var d = $('<div>');
        d.html(data);
        d.dialog({'title':'Search result', width: 900, height: 600, show: {effect: 'fadeIn', duration:800}});
      });
      return false;
    });
  });
</script>


{% endblock %}

banks/templates/depo.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<link rel="stylesheet" href="{% static 'css/ticket.css' %}">

<form action="" method="post" id="depo">
  {% csrf_token %}
  <h2 id="ticket_center">Depo deal</h2>
  <hr>

  
  <div class="errors">
  {% for error in form.non_field_errors %}
  {{ error }}
  {% endfor %}
  </div>

  <br>

  {% for field in form %}
  <div class="textWrapper">
    <br>
    {{field.label_tag}} {{field}}
  </div>
  {% endfor %}
  <br>
  <input type="submit" value="New Depo" class="textWrapper button_form">

  <br>
  <br>
<!--  
  <div style="font-size: 20px;" id="dialog">
    {% for error in form.amount_in_base_cur.errors %}
    {{ error }}
    {% endfor %}
    </div>
  <br>
-->  
</form>

{% endblock %}

banks/templates/graph1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    
<link rel="stylesheet" type="text/css" href="http://cdn.pydata.org/bokeh/release/bokeh-1.2.0.min.css" />
<link rel="stylesheet" type="text/css" href="http://cdn.pydata.org/bokeh/release/bokeh-widgets-1.2.0.min.css" />
<link rel="stylesheet" type="text/css" href="http://cdn.pydata.org/bokeh/release/bokeh-tables-1.2.0.min.css" />

</head>
<body>

    {{ div|safe }}

</body>
<script text="type/javascript" src="http://cdn.pydata.org/bokeh/release/bokeh-1.2.0.min.js"></script>
<script text="type/javascript" src="http://cdn.pydata.org/bokeh/release/bokeh-widgets-1.2.0.min.js"></script>
<script text="type/javascript" src="http://cdn.pydata.org/bokeh/release/bokeh-tables-1.2.0.min.js"></script>
<script text="type/javascript" src="http://cdn.pydata.org/bokeh/release/bokeh-api-1.2.0.min.js"></script>
{{ script | safe }}
</html>

banks/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<title>{{ title }}</title>

    <link rel="stylesheet" href="{% static 'css/home.css' %}">    
    
    <h1> Welcome {{user.first_name}}!!! </h1>
    
    <div id = "homelogo">
        <img  src="{% static "img/orange logo.jpg" %}" width="200px">
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <script> 
            $(document).ready(function(){
                  $("#homelogo").animate({
                  left: '40%',
                  opacity: '1'
                  },
                  {duration: 2000});
            });
    </script> 

{% endblock %}

banks/templates/index.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">

    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    
    <title>Account_{{ title }}</title>

</head>

<body>

  <button class="start_button" onClick="window.location='/accounts/login/'">
    <h1>Liquidity Manager</h1>
  </button>

  <footer>&copy; Copyright 2019 ARW</footer>

</body>

</html>

banks/templates/index1.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">

    <link rel="stylesheet" href="{% static 'css/index1.css' %}">
    
    <title>Account_{{ title }}</title>

</head>

<body>

<!--Hey! This is the original version
of Simple CSS Waves-->

<div class="header">

        <!--Content before waves-->
        <div class="inner-header flex">
        <!--Just the logo.. Don't mind this-->
        <svg version="1.1" class="logo" baseProfile="tiny" id="Layer_1" xmlns="http://www.w3.org/2000/svg"
        xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 500 500" xml:space="preserve">
        <path fill="#FFFFFF" stroke="#000000" stroke-width="10" stroke-miterlimit="10" d="M57,283" />
        
        </svg>
        <h1>Liquidity Manager</h1>
        </div>
        
        <!--Waves Container-->
        <div>
        <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
        viewBox="0 24 150 28" preserveAspectRatio="none" shape-rendering="auto">
        <defs>
        <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z" />
        </defs>
        <g class="parallax">
        <use xlink:href="#gentle-wave" x="48" y="0" fill="rgba(255,255,255,0.7" />
        <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.5)" />
        <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.3)" />
        <use xlink:href="#gentle-wave" x="48" y="7" fill="#fff" />
        </g>
        </svg>
        </div>
        <!--Waves end-->
        
        </div>
        <!--Header ends-->
        
        <!--Content starts-->
        <div class="content flex">
        <p>&copy; Copyright | 2019 | ARW</p>
        </div>
        

</body>

</html>

banks/templates/logout.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<link rel="stylesheet" href="{% static 'css/ticket.css' %}">
<script src="{% static 'js/app.js' %}"></script>

<form action="" method="post">
  {% csrf_token %}
  <h2 id = "ticket_center">Logout Page</h2>
  <hr>
  {% for field in form %}
    <div class="textWrapper">
      <br>
      {{field.label_tag}} {{field}}

    </div>
  {% endfor %}
    <br>
    <p class="textWrapper"><b>{{ user }}</b>, push button below from current session. </p>
  <input type="submit" value="Logout" class="textWrapper button_form">
  <br>
  <br>
</form>

{% endblock %}

banks/templates/marketdataimport.html
{% extends 'base.html' %}

{% block content %}
<br>
<br>
<br>

<h2 id = "dialog"></h2> 

<script>
var txt = "Market Data import succesful. All data downloaded for value date {{ date }}."

      $( function() {$("#dialog").append(txt);
    $( "#dialog" ).dialog({
          show: {
            effect: "blind",
            duration: 500
          }
        }, {
          width: 500
        });
  } );
  </script>
  
{% endblock %}

banks/templates/update_acc.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% load humanize %}
{{ floatvalue|floatformat:2|intcomma }}

<link rel="stylesheet" href="{% static 'css/ticket.css' %}">
<script src="{% static 'js/app.js' %}"></script>

<form method="POST"> {% csrf_token %}
  <h2 id = "ticket_center">Value date details</h2>
  <hr>
  <p class="textWrapper">Date: {{ obj.date|date:'Y-m-d' }}</p>
  <p class="textWrapper">Start: {{ obj.start_balance|floatformat:2 }}</p>
  <p class="textWrapper">End: {{ obj.end_balance|floatformat:2 }}</p>
  <hr>
  {% for field in form %}
  <div class="textWrapper">
    <br>
    {{field.label_tag}} <span class="left">{{field}}</span>

  </div>
  {% endfor %}
  <br>
  <input class="textWrapper button_form" type="submit" value="Save" />
  <br>
  <br>
</form>


{% endblock %}

banks/templates/update_depo.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<link rel="stylesheet" href="{% static 'css/ticket.css' %}">
<script src="{% static 'js/app.js' %}"></script>

{% load humanize %}
    {{ floatvalue|floatformat:2|intcomma }}

<form method="POST"> {% csrf_token %}
    <h2 class = "textWrapper">Depo deal update </h2>
    <p class = "textWrapper">Deal number: {{obj.deal_number}}</p>
    <hr>
{% for field in form %}
    <div class="textWrapper">
      <br>
      {{field.label_tag}} {{field}}

    </div>
  {% endfor %}
<br>
<input class = "textWrapper button_form" type="submit" value="Save"/>
<br>
<br>
</form>

{% endblock %}

banks/templates/upload.html
{% extends 'base.html' %}
{% load static %}

{%  block content %}
<link rel="stylesheet" href="{% static 'css/ticket.css' %}">
<script src="{% static 'js/app.js' %}"></script>

<form method="POST" enctype="multipart/form-data" id="xx">
    <h2 id="ticket_center">Files Upload</h2>
    <hr>
    {% csrf_token %}
    <p class="text textWrapper"> Chose file: </p>
    <br>
    <input class="textWrapper button_form" type="file" name="document">
    <button type="submit" class="button_form">
        Upload file
    </button>
</form>

<h2 id="dialog"></h2>

{% if url %}
<p class="upload">Uploaded file: <a href="{{ url }}"> {{ url }} </a></p>
{% endif %}



<script type="text/javascript">
    var txt = "File uploaded succesfully."

    $("#xx").on('submit', function (event) {
                alert("File uploaded succesfully.");
            });
</script>

{% endblock %}

banks/templates/user_form.html
{% extends "base.html" %}
{% block content %}

<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Add User">
</form>
{% endblock %}